const DEFAULT_ENV = 'es6';
const DEFAULT_ESLINT_PLUGIN_SIMPLE_IMPORT_SORT_FILES = ['./src/**/*'];
const DEFAULT_ESLINT_PLUGIN_IMPORT_RESOLVER_WEBPACK_CONFIG_FILE =
  './webpack/webpack.config.dev.js';

export {
  DEFAULT_ENV,
  DEFAULT_ESLINT_PLUGIN_SIMPLE_IMPORT_SORT_FILES,
  DEFAULT_ESLINT_PLUGIN_IMPORT_RESOLVER_WEBPACK_CONFIG_FILE,
};
