name: Pull Requests Auto-Updates
on:
  push:

jobs:
  auto-update:
    uses: donniean/collections/.github/workflows/pull-requests.auto-update.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
